name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          ## Welcome! Looks like this is your first issue.

          Hey, thanks for your contribution! Please give us a bit of time to review it. 😄

          ## Contact

          Check out the [DoK Slack channel](https://dokcommunity.slack.com/archives/C029SP0H937) for updates and discussion.

          Check out the [Dok YouTube channel](https://www.youtube.com/channel/UCUnXJbHQ89R2uSfKsqQwGvQ) for more information, talks, discussions, and raps!!!
        
          ###### If you like this project, please ⭐ Star it on GitHub to show your love.
        pr-message: |
          ## Welcome! Looks like this is your first pull request.
          
          Hey, thanks for your contribution! Please give us a bit of time to review it. 😄
          
          ## Contact

          Check out the [DoK Slack channel](https://dokcommunity.slack.com/archives/C029SP0H937) for updates and discussion.

          Check out the [Dok YouTube channel](https://www.youtube.com/channel/UCUnXJbHQ89R2uSfKsqQwGvQ) for more information, talks, discussions, and raps!!!

          ###### If you like this project, please ⭐ Star it on GitHub to show your love.
